"""empty message

Revision ID: 25132a7050eb
Revises: 61f6b60d81da
Create Date: 2018-02-06 22:21:20.993832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25132a7050eb'
down_revision = '61f6b60d81da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
